[manager]
sort_by = "alphabetical"
sort_reverse = false
sort_dir_first = true
show_hidden = true
show_symlink = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900

[opener]
folder = [
	{ exec = 'dolphin "$@"', display_name = "Open in File Manager" },
	# { exec = 'xdg-open -R "$@"', display_name = "Open in File Manager" },
	# { exec = 'vim "$@"' },
]
archive = [
	{ exec = '7z x "$1"', block = true, display_name = "Extract here" },
]
text = [
	{ exec = 'helix "$@"', block = true },
]
office = [
	{ exec = 'libreoffice "$@"', block = false, display_name = "Open"},
]
image = [
	# { exec = 'xdg-open "$@"', display_name = "Open" },
	# { exec = 'imv "$@"', display_name = "Open" },
	{ exec = 'nsxiv "$@"', display_name = "Open with nsxiv" },
	{ exec = 'pqiv "$@"', display_name = "Open with pqiv" },
	{ exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show EXIF" },
]
video = [
	{ exec = 'mpv "$@"', block = false, display_name = "Play" },
]
audio = [
	{ exec = 'mpv "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
fallback = [
	{ exec = 'xdg-open "$@"', block = false, display_name = "Open" },
	{ exec = 'xdg-open -R "$@"', block = false, display_name = "Open in File Manager" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },

	{ name = "ts", use = "video" },
	# office
	{ mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = "office" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "inode/x-empty", use = "text" },
	{ mime = "application/json", use = "text" },

	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/vnd.rar", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/zip", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
	{ mime = "application/x-rar", use = "archive" },

	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
