#theme = "onedark"
#theme = "bogster"
# theme = "ayu_mirage"
# theme = "ayu_dark"
# theme = "solarized_light"
theme = "gruvbox_light"
# theme = "gruvbox"
# theme = "gruvbox_dark_hard"
# light
# theme = "spacebones_light"
# theme = "flatwhite"

# lsp.display-inlay-hints = true

[editor]
line-number = "relative"
mouse = false
cursorline = true
# bufferline = "multiple"
rulers = [73, 80, 100]
# code < 80
# doc, comments < 73
# modern max < 100

# Add rulers = [80] to the [editor] section in your config file. In the future, ask questions like this on Matrix or GitHub discussions.
#
# Limit all lines to a maximum of 79 characters.
# For flowing long blocks of text with fewer structural restrictions (docstrings or comments), the line length should be limited to 72 characters.
# Some teams strongly prefer a longer line length. For code maintained exclusively 
## or primarily by a team that can reach agreement on this issue, it is okay to 
## increase the line length limit up to 99 characters, provided that comments and docstrings are still wrapped at 72 characters.

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
# character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.statusline]
# "version-control"
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
