# lsp.display-inlay-hints = true

[[language]]
name = "python"
scope = "source.python"
# language-server = { command = "ruff-lsp" }
language-server = { command = "pylsp" }
# config = { settings = { args = [] } }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true


# [[language]]
# name = "python"
# roots = ["pyproject.toml"]
# language-server = { command = "pyright-langserver", args = ["--stdio"] }
# config = {} # <- this is the important line
# formatter = { command = "black", args = ["--quiet", "-"] }

# [[language]]
# name = "rust"
# auto-format = true
# [language.config]
# checkOnSave = { command = "clippy" }
# cargo clippy
